
// This file has been generated by the GUI designer. Do not modify.
namespace QuoteView
{
	public partial class PortfolioMgr
	{
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.ComboBox comboPortfolios;
		
		private global::Gtk.Entry txtPortfolioName;
		
		private global::Gtk.Button btnNew;
		
		private global::Gtk.Button btnRename;
		
		private global::Gtk.Button btnDelete;
		
		private global::Windows.Controls.ListBox listSymbols;
		
		private global::Gtk.Button buttonCancel;
		
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget QuoteView.PortfolioMgr
			this.Name = "QuoteView.PortfolioMgr";
			this.Title = global::Mono.Unix.Catalog.GetString ("Manage Portfolios");
			this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-preferences", global::Gtk.IconSize.Menu);
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			// Internal child QuoteView.PortfolioMgr.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			this.vbox2.BorderWidth = ((uint)(3));
			// Container child vbox2.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.Xpad = 6;
			this.label1.Xalign = 0F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Portfolio Name");
			this.vbox2.Add (this.label1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.comboPortfolios = global::Gtk.ComboBox.NewText ();
			this.comboPortfolios.TooltipMarkup = "Select Portfolio to edit";
			this.comboPortfolios.Name = "comboPortfolios";
			this.hbox2.Add (this.comboPortfolios);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.comboPortfolios]));
			w3.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.txtPortfolioName = new global::Gtk.Entry ();
			this.txtPortfolioName.TooltipMarkup = "Enter new name";
			this.txtPortfolioName.CanFocus = true;
			this.txtPortfolioName.Name = "txtPortfolioName";
			this.txtPortfolioName.Text = global::Mono.Unix.Catalog.GetString ("Enter new name here, add one symbol to complete...");
			this.txtPortfolioName.IsEditable = true;
			this.txtPortfolioName.MaxLength = 100;
			this.txtPortfolioName.InvisibleChar = '●';
			this.hbox2.Add (this.txtPortfolioName);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.txtPortfolioName]));
			w4.Position = 1;
			// Container child hbox2.Gtk.Box+BoxChild
			this.btnNew = new global::Gtk.Button ();
			this.btnNew.TooltipMarkup = "New Portfolio";
			this.btnNew.WidthRequest = 0;
			this.btnNew.CanFocus = true;
			this.btnNew.Name = "btnNew";
			this.btnNew.UseUnderline = true;
			this.btnNew.Relief = ((global::Gtk.ReliefStyle)(2));
			global::Gtk.Image w5 = new global::Gtk.Image ();
			w5.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-new", global::Gtk.IconSize.Menu);
			this.btnNew.Image = w5;
			this.hbox2.Add (this.btnNew);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.btnNew]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.btnRename = new global::Gtk.Button ();
			this.btnRename.TooltipMarkup = "Rename portfolio";
			this.btnRename.CanFocus = true;
			this.btnRename.Name = "btnRename";
			this.btnRename.UseUnderline = true;
			this.btnRename.Relief = ((global::Gtk.ReliefStyle)(2));
			global::Gtk.Image w7 = new global::Gtk.Image ();
			w7.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("QuoteView.Resources.rename-unlocked.png");
			this.btnRename.Image = w7;
			this.hbox2.Add (this.btnRename);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.btnRename]));
			w8.Position = 3;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.btnDelete = new global::Gtk.Button ();
			this.btnDelete.TooltipMarkup = "Delete portfolio";
			this.btnDelete.CanFocus = true;
			this.btnDelete.Name = "btnDelete";
			this.btnDelete.UseUnderline = true;
			this.btnDelete.Relief = ((global::Gtk.ReliefStyle)(2));
			global::Gtk.Image w9 = new global::Gtk.Image ();
			w9.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-remove", global::Gtk.IconSize.Button);
			this.btnDelete.Image = w9;
			this.hbox2.Add (this.btnDelete);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.btnDelete]));
			w10.Position = 4;
			w10.Expand = false;
			w10.Fill = false;
			this.vbox2.Add (this.hbox2);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.listSymbols = new global::Windows.Controls.ListBox ();
			this.listSymbols.Events = ((global::Gdk.EventMask)(256));
			this.listSymbols.Name = "listSymbols";
			this.vbox2.Add (this.listSymbols);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.listSymbols]));
			w12.Position = 2;
			w1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox2]));
			w13.Position = 0;
			// Internal child QuoteView.PortfolioMgr.ActionArea
			global::Gtk.HButtonBox w14 = this.ActionArea;
			w14.Name = "dialog1_ActionArea";
			w14.Spacing = 10;
			w14.BorderWidth = ((uint)(5));
			w14.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Relief = ((global::Gtk.ReliefStyle)(2));
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w15 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w14 [this.buttonCancel]));
			w15.Expand = false;
			w15.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Relief = ((global::Gtk.ReliefStyle)(2));
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w16 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w14 [this.buttonOk]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 370;
			this.txtPortfolioName.Hide ();
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.comboPortfolios.Changed += new global::System.EventHandler (this.OnComboPortfoliosChanged);
			this.txtPortfolioName.Changed += new global::System.EventHandler (this.OnTxtPortfolioNameChanged);
			this.btnNew.Clicked += new global::System.EventHandler (this.OnBtnNewClicked);
			this.btnRename.Clicked += new global::System.EventHandler (this.OnBtnRenameClicked);
			this.btnDelete.Clicked += new global::System.EventHandler (this.OnBtnDeleteClicked);
			this.buttonCancel.Clicked += new global::System.EventHandler (this.OnButtonCancelClicked);
			this.buttonOk.Clicked += new global::System.EventHandler (this.OnButtonOkClicked);
		}
	}
}
