
// This file has been generated by the GUI designer. Do not modify.
namespace Windows.Controls
{
	public partial class ListBox
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.ComboBoxEntry comboboxentry;
		
		private global::Gtk.Button btnAdd;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TreeView listbox;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Windows.Controls.ListBox
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Windows.Controls.ListBox";
			// Container child Windows.Controls.ListBox.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.comboboxentry = global::Gtk.ComboBoxEntry.NewText ();
			this.comboboxentry.Name = "comboboxentry";
			this.hbox1.Add (this.comboboxentry);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.comboboxentry]));
			w1.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnAdd = new global::Gtk.Button ();
			this.btnAdd.CanDefault = true;
			this.btnAdd.CanFocus = true;
			this.btnAdd.Name = "btnAdd";
			this.btnAdd.Relief = ((global::Gtk.ReliefStyle)(2));
			global::Gtk.Image w2 = new global::Gtk.Image ();
			w2.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			this.btnAdd.Image = w2;
			this.hbox1.Add (this.btnAdd);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnAdd]));
			w3.Position = 1;
			w3.Expand = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.listbox = new global::Gtk.TreeView ();
			this.listbox.TooltipMarkup = "Press delete to remove symbols from portfolio.";
			this.listbox.CanFocus = true;
			this.listbox.Name = "listbox";
			this.listbox.HoverSelection = true;
			this.GtkScrolledWindow.Add (this.listbox);
			this.vbox1.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
			w6.Position = 1;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.comboboxentry.Changed += new global::System.EventHandler (this.OnComboboxentryChanged);
			this.btnAdd.Clicked += new global::System.EventHandler (this.OnBtnAddClicked);
			this.listbox.KeyReleaseEvent += new global::Gtk.KeyReleaseEventHandler (this.OnListboxKeyReleaseEvent);
		}
	}
}
